version: "3"
services:
  strapi:
    container_name: strapi
    build: 
      context: ../api
      dockerfile: Dockerfile
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_FILENAME: ${DATABASE_FILENAME}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ../api/config:/opt/app/config
      - ../api/src:/opt/app/src
      - ../api/package.json:/opt/package.json
      - ../api/package-lock.json:/opt/package-lock.json
      - ../api/.tmp:/opt/app/.tmp      
      - ../api/public/uploads:/opt/app/public/uploads
    ports:
      - "127.0.0.1:1337:1337"
